### DISCUSSION TITLE
MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb

### DISCUSSION THREAD

**Discussion by itheynamesoimnotgenderracial** [docker-library/mongo#568] [General]
Good day sir. 
Please assist me with this issue when connecting mongo docker to the mongoose to start the server. I'm new to docker and I'm trying to connect mongo docker to mongoose but apparently, things are not working so well. Your assistance would be highly appreciated.

```
Error:

> MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb
>     at NativeConnection.Connection.openUri (/home/app/node_modules/mongoose/lib/connection.js:824:32)
>     at /home/app/node_modules/mongoose/lib/index.js:380:10
>     at /home/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
>     at new Promise (<anonymous>)
>     at promiseOrCallback (/home/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
>     at Mongoose._promiseOrCallback (/home/app/node_modules/mongoose/lib/index.js:1225:10)
>     at Mongoose.connect (/home/app/node_modules/mongoose/lib/index.js:379:20)
>     at connectDB (/home/app/connections/database.js:4:18)
>     at start (/home/app/server.js:31:9)
>     at Object.<anonymous> (/home/app/server.js:39:1) {
>   reason: TopologyDescription {
>     type: 'Unknown',
>     servers: Map(1) { 'mongodb:27017' => [ServerDescription] },
>     stale: false,
>     compatible: true,
>     heartbeatFrequencyMS: 10000,
>     localThresholdMS: 15,
>     logicalSessionTimeoutMinutes: undefined
>   },
>   code: undefined
> }
```

mongo.yaml
```yaml
version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_HOSTNAME=localhost
```      
      
server.js
```js
const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const path = require("path");

// Routes and controllers
const router = require("./routes/route");
const controller = require("./controllers/controller");
const connectDB = require("./connections/database");
const User = require("./models/User");

app.use(express.json());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
	extended: true,
	limit: "100000mb",
	parameterLimit: 10000000
}));

app.use("/public", express.static(path.join(__dirname, "assets")));
app.set("views", __dirname + "/views");
app.set("view engine", "ejs");
app.get("/", async (req, res) => {
	res.render("index");
});

app.use("/api/v1/test", router);
const PORT = 3000;
const start = async () => {
	try {
		await connectDB("mongodb://admin:password@mongodb");
		app.listen(PORT, () => console.log(`Server is listening to port ${PORT}`));
	} catch(error) {
		console.log(error);
		return error;
	}
}

start();
```

Thank you.

**Comment by wglambert** [comment]
Your same issue? https://www.reddit.com/r/mongodb/comments/x5h9cw/mongooseserverselectionerror_getaddrinfo_eai/

Seems like the mongo container isn't running, what do the logs show for that one?

I'm not able to reproduce with your docker-compose file
```console
$ docker-compose up -d
Creating mongo_mongodb_1 ... done
Creating mongo_mongo-express_1 ... done

$ docker-compose logs 2>&1 | tail -n 5
mongodb_1        | {"t":{"$date":"2022-09-06T16:02:09.195+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
mongodb_1        | {"t":{"$date":"2022-09-06T16:02:09.195+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
mongodb_1        | {"t":{"$date":"2022-09-06T16:02:11.667+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.27.0.3:50582","uuid":"ee51f193-d383-4c21-b60a-8a6fbd0bd881","connectionId":1,"connectionCount":1}}
mongodb_1        | {"t":{"$date":"2022-09-06T16:02:11.681+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"172.27.0.3:50582","client":"conn1","doc":{"driver":{"name":"nodejs","version":"3.7.3"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-18-amd64"},"platform":"'Node.js v12.22.7, LE (legacy)"}}}
mongodb_1        | {"t":{"$date":"2022-09-06T16:02:11.712+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn1","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"admin","authenticationDatabase":"admin","remote":"172.27.0.3:50582","extraInfo":{}}}
```

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by LaurentGoderre** [comment]
In addition to `depends_on` which controls the order containers are started, you need to add `links` to map the host name in the container.

```yaml
version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb
    links:
      - mongodb
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      # - ME_CONFIG_MONGODB_HOSTNAME=localhost
  ```

**Reply by LaurentGoderre** [reply]
Although, you can just use links and not depends_on because links will cause an implicit `depends_on`

**Comment by kanaan-dvlps** [comment]
I still have the problem
docker-compose.yml
```yaml
version: "3.8"
services:
  booking_system_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    stop_signal: SIGINT
    container_name: booking_system_service
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_CONNECTION_URL: ${POSTGRES_CONNECTION_URL}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_CONNECTION_URL: ${MONGO_CONNECTION_URL}
      APP_PORT: ${APP_PORT}
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    depends_on:
      - booking_system_postgres_db_service
      - booking_system_mongodb_service
    links:
      - booking_system_postgres_db_service
      - booking_system_mongodb_service
    network_mode: "host"
    restart: always

  booking_system_postgres_db_service:
    image: postgres:13.15
    container_name: booking_system_postgres_db_service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    network_mode: "host"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  booking_system_mongodb_service:
    image: mongo:latest
    container_name: booking_system_mongodb
    environment:
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
    volumes:
      - /data/db:/data/db
    network_mode: "host"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"]
      interval: 10s
      timeout: 5s
      retries: 5
```

Dockerfile
```Dockerfile
# Stage 1: Build
FROM node:20.14.0 As build

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src

RUN npm install
RUN npm run build
RUN rm -rf .npmrc

# Stage 2: Production
FROM node:lts-alpine@sha256:34b7aa411056c85dbf71d240d26516949b3f72b318d796c26b57caaa1df5639a As production

RUN apk add dumb-init
RUN npm install -g nodemon
ENV NODE_ENV=production

# Create necessary directories and set permissions
RUN mkdir -p /app/var/lib/postgresql/data /app/data/db && \
    chown -R node:node /app/var/lib/postgresql/data /app/data/db

USER node
WORKDIR /app
COPY --chown=node:node --from=build /app/node_modules ./node_modules
COPY --chown=node:node --from=build /app/dist ./dist
COPY --chown=node:node . /app

EXPOSE 5000
CMD ["dumb-init", "npm", "run", "dev"]
```

.env
```
# Environment variables for the development environment
# This file should be included in the .gitignore file

POSTGRES_HOST=booking_system_postgres_db_service
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=booking_system_db
POSTGRES_CONNECTION_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

MONGO_PORT=27017
MONGO_DB_HOST=booking_system_mongodb
MONGO_DB_NAME=booking_system
# MONGO_CONNECTION_URL=mongodb://${MONGO_DB_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}
MONGO_CONNECTION_URL=mongodb://booking_system_mongodb:27017/booking_system

APP_PORT=5000
```
