### DISCUSSION TITLE
What is the correct way to overwrite `CMD` without getting "You are running this process as the root user"?

### DISCUSSION THREAD

**Discussion by simon-liebehenschel** [docker-library/mongo#645] [General]
## Maybe related issues

- https://github.com/docker-library/mongo/issues/186
- https://github.com/docker-library/mongo/issues/315
- https://github.com/docker-library/mongo/pull/81/files

### Attempt 1

```yaml
services:
  mongo:
    image: mongo:7.0.2
    ports:
      - 27017
    command: ["timeout", "43200" "mongod"]
```

gives 

```
You are running this process as the root user, which is not recommended
```

 so I think my `command` is wrong.

### Attempt 2

```yaml
services:
  mongo:
    image: mongo:7.0.2
    ports:
      - 27017
    command: ["sh", "-c", "chown -R mongodb:mongodb /data/db/ && su - mongodb -c 'mongod'"]
```

gives some warnings too:

```
"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."

"This server is bound to localhost. Remote systems will be unable to connect to this server. Start the server with --bind_ip <address> to specify which IP addresses it should serve responses from, or with --bind_ip_all to bind to all interfaces. If this behavior is desired, start the server with --bind_ip 127.0.0.1 to disable this warning","tags":["startupWarnings"]

"Soft rlimits for open file descriptors too low","attr":{"currentValue":1024,"recommendedMinimum":64000},"tags":["startupWarnings"]
```

I still think that I override `CMD` incorrectly. Any suggestions?

**Comment by LaurentGoderre** [comment]
That compose file works for me

**Reply by simon-liebehenschel** [reply]
Both examples  work, but the first example gives  "You are running this process as the root user, which is not recommended" in the log which is not expected.

The second example works too, but it gives some unique warnings too which I did not see when I run just `mongo` image without overwriting.

**Reply by LaurentGoderre** [reply]
Adding the `user` setting removes this warning

```yaml
services:
  mongo:
    image: mongo:7.0.2
    ports:
      - 27017
    user: mongodb
    command: ["timeout", "43200", "mongod"]
```
