### DISCUSSION TITLE
Why add originalArgOne=mongod to environment variables

### DISCUSSION THREAD

**Discussion by dufu-byte** [docker-library/mongo#702] [General]
What I'm doing now
```yml
services:
  mongo-7.0.0-server:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: mongo-7.0.0-server
    restart: always
    privileged: true
    environment:
      - originalArgOne=mongod
      - MONGO_INITDB_ROOT_USERNAME=zzroot
      - MONGO_INITDB_ROOT_PASSWORD=111111111111111
    ports:
      - 20017:27017
    volumes:
      - ./db:/data/db
      - ./configdb/mongod.conf:/data/configdb/mongod.conf
      - ./mongodbLog:/var/log/mongodb/
    command:
      - --wiredTigerCacheSizeGB
      - '1.5'
```
Is there another way?
