### ISSUE TITLE
docker mongodb replica keyfile Permission denied

### ISSUE THREAD

**Issue by Jaware** [docker-library/mongo#13]
i use keyfile as  docker mongodb replica security tool, however when run with  -v /data/mongo/keyfile:/data/keyfile,it showed   keyfile Permission denied ,the keyfile is 600(mongo need)

**Comment by yosifkit** [comment]
The permission mask should be fine, but the file will need to be owned by the mongodb user in the container (uid=999(mongodb) gid=999(mongodb)).

**Comment by Jaware** [comment]
sorry ，i do not know how to do that,can you explain a little more clear

**Comment by yosifkit** [comment]
You'll just need to `chown 999:999 keyfile` before you run the docker container (you probably need `sudo` in there).

**Comment by Jaware** [comment]
thanks,sorry too busy these days

**Comment by oxr463** [comment]
@yosifkit how can I do that from my docker-compose.yml file?

```yaml
  db:
    image: mongo:4.4.3
    hostname: mongo-db-001
    command: --replSet bg0 --keyFile /etc/mongodb.key
    volumes:
      - ./mongodb.key:/etc/mongodb.key
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'foo'
      MONGO_INITDB_ROOT_PASSWORD: 'bar'
      MONGO_INITDB_DATABASE: baz
```
