### ISSUE TITLE
Port mapping doesnt work via docker-compose 

### ISSUE THREAD

**Issue by aldarund** [docker-library/mongo#210]
It work via docker, but doesnt work via docker-compose.
Compose file
```
    version: '3'
    services:
      mongo:
        image: mongo
        ports:
          - 27017:21017
```
docker command that works fine

`docker run  --name my_mongo -d -p 27017:27017 mongo
`

Full details are here
https://stackoverflow.com/q/46922237/239354

Is there any workaround for it? Is it a bug in the image?
