### ISSUE TITLE
Port 27017 is hardcoded in Dockerfile

### ISSUE THREAD

**Issue by romaklimenko** [docker-library/mongo#212]
See https://github.com/docker-library/mongo/blob/c501968a9c330a773a2bc2c9b67dcd4ebbb58651/3.5/Dockerfile#L76 for example.

My compose file for a replica set looks like this:
```
version: "3"
services:
  xyz-replica-set-0:
    image: mongo:unstable
    command: mongod --replSet xyz --dbpath /data/db --logappend --oplogSize 64 --noauth --bind_ip_all
    ports:
      - "27000:27017"
  xyz-replica-set-1:
    image: mongo:unstable
    command: mongod --replSet xyz --dbpath /data/db --logappend --oplogSize 64 --noauth --bind_ip_all
    ports:
      - "27001:27017"
```

This means that I can connect to `xyz-replica-set-1` as `mongodb://localhost:27001`, but `rs.status()` shows me `xyz-replica-set-1:27017`. Is any way to work it around? Could you please add an option to specify a port number for a container to expose?
