### ISSUE TITLE
Can't connect to Mongo instance after initialization of replica set

### ISSUE THREAD

**Issue by YashchenkoN** [docker-library/mongo#249]
I use ```mongo:latest``` image. My ```docker-compose.yml``` looks like this:

```
version: '3.3'

services:
  java-app:
    image: java-app:latest
    depends_on:
      - elasticsearch
      - mongo
    environment:
      - WAIT_HOSTS=elasticsearch:9200,mongo:27017
    ports:
      - "8080:8080"

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch

  mongo_connector:
    build:
      ./mongo-connector
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - WAIT_HOSTS=elasticsearch:9200,mongo:27017

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
```

In this case, java-app is able to connect to mongo container. But I need to run mongo with --replSet argument to get mongo-connector working, so I've added this argument using ```command``` option:

```
mongo:
  image: mongo:latest
  command: ["mongod", "--replSet", "rs0"]
  ports:
    - "27017:27017"
```

After that my application is still able to connect to the instance, but mongo-connector doesn't work since replica set is not initiated. To initiate replica set, I've changed ```command```:

```
  mongo:
    image: mongo:latest
    command: ["sh", "-c", "mongod --replSet rs0 && mongo admin --eval 'rs.initiate();'"]
    ports:
      - "27017:27017"
```

I see the following message in output:
```
mongo_1  | 2018-03-03T20:59:33.783+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
```

Despite that, the java-app throws an exception because it can't connect to the instance. Also, I can't connect to the mongo from the terminal.

Could you please advise, what's wrong?
