### ISSUE TITLE
docker-compose mongo volume

### ISSUE THREAD

**Issue by herrmondlicht** [docker-library/mongo#270]
Hello, fellows!

I'm trying to use `docker-compose` to run a composition with node server and a mongodb which must use a docker volume to store its data. However, after I execute the `docker-compose down` command, I lost all data that I've saved once before. When I `docker volume list`, I'm able to list the volume created by my `docker-compose`. 

I don't want to set a place in the host to have my mongo data, if I use the ./data path as volume, data is persistent. However I want to easily manipulate it with `docker volume` and such..

Here's a sample 

```
version: '3.4'
services:
  nodeserver:
    build: .
    container_name: "c-name"
    ports:
      - 3001:3001
      - 80:80
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mvertes/alpine-mongo
    volumes:
      - mongo-data:/var/data
    container_name: "mongodb-service"
    ports:
     - 27017:27017
volumes:
  mongo-data:
```

Thanks in advance
