### ISSUE TITLE
WiredTiger "handle-open: open: File exists" error when using NFS persistent storage

### ISSUE THREAD

**Issue by sdanieru** [docker-library/mongo#328]
Greetings folks,
I'm attempting to use the standard mongo image to deploy mongodb in kubernetes w/ NFS persistent storage. The persistent volume claims are created just fine, but then the container fails with the following error:

`2019-01-30T19:55:47.124+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1548878147:124885][32:0x7fc836649600], connection: __posix_open_file, 715: /data/db/WiredTiger.wt: handle-open: open: File exists
2019-01-30T19:55:47.126+0000 I STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.7
2019-01-30T19:55:47.127+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1548878147:127706][32:0x7fc836649600], connection: __posix_open_file, 715: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
2019-01-30T19:55:47.128+0000 E -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 424
2019-01-30T19:55:47.129+0000 I STORAGE  [initandlisten] exception in initAndListen: Location28595: 1: Operation not permitted, terminating`

My guess is that the underlying NFS filesystem is behaving in a way that mongo doesn't like. The mongo docs do talk about NFS briefly and say 

> If you decide to use NFS, add the following NFS options to your /etc/fstab file: bg, nolock, and noatime

but since I'm using the helm chart `mongodb-replicaset` I don't see a way to configure this on the client side.

Anyone successfully running mongo containers on kubernetes with underlying NFS for persistent storage? What NFS server settings are you using to get it to work?

**Comment by wglambert** [comment]
How are the permissions on your NFS set? https://github.com/docker-library/mariadb/issues/205
There was also this permissions issue using kubernetes that might be relevant https://github.com/docker-library/mongo/issues/127

You could also try asking over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by sdanieru** [comment]
I double-checked permissions and there were some issues there that I got sorted out, thanks!

**Comment by ChinaSilence** [comment]
how do you resolve it   on kubernetes ?

**Comment by wglambert** [comment]
You give the folder you're mounting permissions for the user that mongo is running as in the container. So `mongodb:mongodb` or `999:999`.

And then you can get your PVC and PV like:
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.29.0.218
    path: /test/nfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```
In this instance I made the folder `/test/nfs` and the `nfs` folder is owned by `999:999`. I can mount that to another host and use it as user 999

And then in your deployment.yaml you'll throw something like this in:
```yaml
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: "IfNotPresent"
          env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: mango
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: bongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo-db
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-pvc
```

**Comment by wglambert** [comment]
I also had to run the container as `999:999`, as the running user is normally root which may not have access to everything (even if the empty nfs folder was 777 permissions)
Without that on initialization I was getting:
```console
$ kubectl logs mongo-fc76c984d-jsckf 
find: '/data/db/journal': Permission denied
find: '/data/db/diagnostic.data': Permission denied
```
The permissions were indiscernible from a non-nfs blank initialization but I guess some underlying nfs auth was disallowing the `root` user from accessing certain things
I mounted the initialized nfs volume as `db1` and compared
```console
root@mongo-67bb75f79c-4dr6q:/data# ls -al
total 20
drwxr-xr-x  5 root    root    4096 Jul 30 20:17 .
drwxr-xr-x 60 root    root    4096 Jul 30 20:17 ..
drwxr-xr-x  2 mongodb mongodb 4096 Jul 29 23:48 configdb
drwxr-xr-x  4 mongodb mongodb 4096 Jul 30 20:18 db
drwxrwxrwx  4 mongodb mongodb 4096 Jul 30 20:09 db1

root@mongo-67bb75f79c-4dr6q:/data# diff -y <(ls -al db) <(ls -al db1)
total 352                                                     | total 344
drwxr-xr-x 4 mongodb mongodb  4096 Jul 30 20:19 .             | drwxrwxrwx 4 mongodb mongodb  4096 Jul 30 20:09 .
drwxr-xr-x 5 root    root     4096 Jul 30 20:17 ..              drwxr-xr-x 5 root    root     4096 Jul 30 20:17 ..
-rw------- 1 mongodb mongodb    45 Jul 30 20:17 WiredTiger    | -rw------- 1 mongodb mongodb    45 Jul 30 20:08 WiredTiger
-rw------- 1 mongodb mongodb    21 Jul 30 20:17 WiredTiger.lo | -rw------- 1 mongodb mongodb    21 Jul 30 20:08 WiredTiger.lo
-rw------- 1 mongodb mongodb  1064 Jul 30 20:19 WiredTiger.tu | -rw------- 1 mongodb mongodb  1064 Jul 30 20:09 WiredTiger.tu
-rw------- 1 mongodb mongodb 69632 Jul 30 20:19 WiredTiger.wt | -rw------- 1 mongodb mongodb 69632 Jul 30 20:09 WiredTiger.wt
-rw------- 1 mongodb mongodb  4096 Jul 30 20:17 WiredTigerLAS | -rw------- 1 mongodb mongodb  4096 Jul 30 20:09 WiredTigerLAS
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 _mdb_catalog. | -rw------- 1 mongodb mongodb 16384 Jul 30 20:09 _mdb_catalog.
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 collection-0- | -rw------- 1 mongodb mongodb 16384 Jul 30 20:09 collection-0-
-rw------- 1 mongodb mongodb 32768 Jul 30 20:18 collection-2- | -rw------- 1 mongodb mongodb 32768 Jul 30 20:08 collection-2-
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 collection-4- | -rw------- 1 mongodb mongodb 16384 Jul 30 20:08 collection-4-
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 collection-7- | -rw------- 1 mongodb mongodb 16384 Jul 30 20:09 collection-7-
drwx------ 2 mongodb mongodb  4096 Jul 30 20:24 diagnostic.da | drwx------ 2 mongodb mongodb  4096 Jul 30 20:08 diagnostic.da
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 index-1--7734 | -rw------- 1 mongodb mongodb 16384 Jul 30 20:08 index-1-47937
-rw------- 1 mongodb mongodb 32768 Jul 30 20:18 index-3--7734 | -rw------- 1 mongodb mongodb 32768 Jul 30 20:08 index-3-47937
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 index-5--7734 | -rw------- 1 mongodb mongodb 16384 Jul 30 20:08 index-5-47937
-rw------- 1 mongodb mongodb 16384 Jul 30 20:18 index-6--7734 | -rw------- 1 mongodb mongodb 16384 Jul 30 20:08 index-6-47937
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 index-8--7734 | -rw------- 1 mongodb mongodb 16384 Jul 30 20:08 index-8-47937
-rw------- 1 mongodb mongodb 16384 Jul 30 20:17 index-9--7734 | -rw------- 1 mongodb mongodb 16384 Jul 30 20:08 index-9-47937
drwx------ 2 mongodb mongodb  4096 Jul 30 20:17 journal       | drwx------ 2 mongodb mongodb  4096 Jul 30 20:08 journal
-rw------- 1 mongodb mongodb     2 Jul 30 20:17 mongod.lock   | -rw------- 1 mongodb mongodb     0 Jul 30 20:09 mongod.lock
-rw------- 1 mongodb mongodb 32768 Jul 30 20:19 sizeStorer.wt | -rw------- 1 mongodb mongodb 32768 Jul 30 20:09 sizeStorer.wt
-rw------- 1 mongodb mongodb   114 Jul 30 20:17 storage.bson  | -rw------- 1 mongodb mongodb   114 Jul 30 20:08 storage.bson
```

So my working `mongo.yaml` is
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: "IfNotPresent"
          env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: mango
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: bongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo-db
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-pvc
```

In addition to the pv/pvc yaml for the volume
