### ISSUE TITLE
How to customize the configuration file by docker-compose.yml?

### ISSUE THREAD

**Issue by quasipaa** [docker-library/mongo#359]
I want to start the mongodb service in docker-compose.yml and specify the database directory and log file output through a custom configuration file. How do I do this?

**Comment by quasipaa** [comment]
docker-compose.yml
```yml
version: "3"
services:
  mongod:
    image: mongo:4.1.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    deploy:
      replicas: 1
    volumes:
      - /root/data/mongod:/root/data
      - /root/logs/mongod:/root/logs
      - ./mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    command: --config /etc/mongod.conf
```

mongod.conf
```yml
systemLog:
  verbosity: 0
  destination: file
  path: /root/logs/mongod.log
  timeStampFormat: iso8601-utc
storage:
  directoryPerDB: true
  dbPath: /root/data
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1
  journal:
    enabled: true
processManagement:
  fork: true
net:
  port: 27017
  bindIp: 0.0.0.0
security:
  authorization: enabled
```

I can't start this service.
