### ISSUE TITLE
Not able to connect MongoDB every time am getting Unauthorized 

### ISSUE THREAD

**Issue by repo-gsr** [docker-library/mongo#397]
Hi,

i created one docker-compose file to build my application and also to connect mongodb container.

but am getting unauthorized exception when am hitting any url in to my applictaion .

Please find the following docker-compose file.

```yaml
version: '3.1'
services:
  myapp:
    image: employee-management
    container_name: employee-management
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./tmp/employeemngt
    ports:
    - 8082:8081
    links:
    - mongo
    depends_on:
    - mongo
    networks:
    - mongo_net
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: employee-management
      MONGO_INITDB_ROOT_USERNAME: myUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: abc123
    ports:
    - 27017:27017
    volumes:
    - ./user.js:/docker-entrypoint-initdb.d/user.js:ro
    networks:
    - mongo_net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myUserAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
    - mongo_net
    depends_on:
    - mongo
networks:
  mongo_net:
    driver: bridge
```

Please find the Issue am getting while hitting my application.

```
 org.apache.juli.logging.DirectJDKLog: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 13: 'command insert requires authentication' on server mongo:27017. The full response is { "ok" : 0.0, "errmsg" : "command insert requires authentication", "code" : 13, "codeName" : "Unauthorized" }; nested exception is com.mongodb.MongoCommandException: Command failed with error 13: 'command insert requires authentication' on server mongo:27017. The full response is { "ok" : 0.0, "errmsg" : "command insert requires authentication", "code" : 13, "codeName" : "Unauthorized" }] with root cause
employee-management | com.mongodb.MongoCommandException: Command failed with error 13: 'command insert requires authentication' on server mongo:27017. The full response is { "ok" : 0.0, "errmsg" : "command insert requires authentication", "code" : 13, "codeName" : "Unauthorized" }
```
