### ISSUE TITLE
User is not created during execution of init script

### ISSUE THREAD

**Issue by ArtemeeSenin** [docker-library/mongo#399]
In init script in `/docker-entrypoint-initdb.d/mongo-init.sh` collections are created but not user in `MONGO_INITDB_DATABASE`

docker-compose.yml
```
version: '3.7'

services:
    mongodb:
        user: $UID
        image: mongo:bionic
        ports:
          - '27017:27017'
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: secret
          MONGO_INITDB_DATABASE: data
          MONGO_INITDB_USERNAME: user
          MONGO_INITDB_PASSWORD: secret
        volumes:
          - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
          - ./data/:/data/db
```

mongo-init.sh
```
mongo -- "$MONGO_INITDB_DATABASE" <<EOF
    var database = db.getSiblingDB('$MONGO_INITDB_DATABASE');
    var user = '$(cat "$MONGO_INITDB_USERNAME")';
    var passwd = '$(cat "$MONGO_INITDB_PASSWORD")';
    database.createUser({user: user, pwd: passwd, roles: ["readWrite"]});
    database.createCollection('stories');
EOF
```

Admin user is initialized correctly and collection in `data` database was created but the `user` was not created. Collection `stories` is created in `data` database so I expected to have a user created also after this script was run

After docker exec at mongo instance I see
```
> use data
switched to db data
> show collections
stories
> show users
> 
```

Thanks in advance!

P.S
I also tried to auth as admin at first but this  had no effect
```
#!/bin/bash

mongo -- "$MONGO_INITDB_DATABASE" <<EOF
    var rootUser = '$(cat "$MONGO_INITDB_ROOT_USERNAME_FILE")';
    var rootPassword = '$(cat "$MONGO_INITDB_ROOT_PASSWORD_FILE")';
    var admin = db.getSiblingDB('admin');
    admin.auth(rootUser, rootPassword);    

    var user = '$(cat "$MONGO_INITDB_USERNAME")';
    var passwd = '$(cat "$MONGO_INITDB_PASSWORD")';
    db.createUser({user: user, pwd: passwd, roles: ["readWrite"]});
    db.createCollection('stories');
EOF
```
