### ISSUE TITLE
MONGO_INITDB_DATABASE and directory docker-entrypoint-initdb.d not running. 

### ISSUE THREAD

**Issue by theabner** [docker-library/mongo#429]
I am trying to create a database with the MONGO_INITDB_DATABASE command but it is not being created. I'm also trying to create a user from a mongo-init.js javascript within the /docker-entrypoint-initdb.d directory but it doesn't work either. I'm using a mongo image: 4.4.1

Does anyone know what can it be?

docker-compose.yml
```
version: "3.1"

networks:
  database:
  server:
  client:

services:
  db:
    image: mongo:4.4.1
    container_name: Banco-de-Dados
    restart: always
    command: --auth
    environment:
      MONGO_INITDB_DATABASE: collabty
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste
    ports:
      - 22222:27017
    volumes:
      - ./Server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - dbdata:/data/db
    networks:
      - database

volumes:
  dbdata:
```
mongo-init.js

```
db.auth('root', 'teste')

db = db.getSiblingDB('test-database')

db.createUser({
  user: "theabnermatheus",
  pwd: "teste",
  roles: [{role: "readWrite", db: "collabty"}]
});

```

I checked the directories and everything is correct, I entered the container and navigated to the /docker-entrypoint-initdb.d directory and the mongo-init.js file is inside, however the script is not creating the user.
