### ISSUE TITLE
It did not work when I bound mount a local filesystem to container on Linux

### ISSUE THREAD

**Issue by shanezhiu** [docker-library/mongo#430]
## Environment

Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye

## local filesystem info
File: data/
  Size: 166             Blocks: 0          IO Block: 4096   directory
Device: 3dh/61d Inode: 40657089    Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-10-27 21:00:34.383395930 +0800
Modify: 2020-10-27 20:58:55.955035295 +0800
Change: 2020-10-27 21:00:25.615364085 +0800
 Birth: 2020-10-27 19:55:34.320386231 +0800

## Dockerfile
```
FROM mongo:4.4.1-bionic

LABEL MAINTAINER="shanezhiu <shanezhiu@gmail.com>"

ENTRYPOINT [ "mongod", "--config", "/etc/mongod.conf"]
```
## docker-compose.yml
```
version: "3.8"

services: 
    mongo:
        build: ./
        restart: "always"
        expose: 
            - "27017"
            - "27016"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: test
            MONGO_INITDB_ROOT_PASSWORD: test
        volumes: 
            - "./conf/mongod.conf:/etc/mongod.conf"
            - "./data:/var/lib/mongodb"
            - "./log:/var/log/mongodb"

        networks: 
            mongo_service:
                ipv4_address: 172.23.0.2
                ipv6_address: 2001:3984:3989::1

networks: 
    mongo_service:
        driver: bridge
        ipam:
            config:
                - subnet: "172.23.0.0/16"
                - subnet: "2001:3984:3989::/64"

```
## mongod.conf

```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
  fork: true

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:

```

## error-log
`
{"t":{"$date":"2020-10-27T13:00:37.594+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1603803637:594335][7:0x7f382c6b4a80], connection: __wt_cache_destroy, 369: cache server: exiting with 2 pages in memory and 0 pages evicted"}}`

## question

By searching this error-log from goole, I know that binding mout method may fail on Windows or Mac.

But there is not any explains about how and why does it occurs on Linux.

## reference
https://github.com/strapi/strapi-docker/issues/80
