### ISSUE TITLE
unable to import/require npm packages inside mongodb container on startup

### ISSUE THREAD

**Issue by kevinmachstudio** [docker-library/mongo#434]
would like to use FakerJS https://github.com/marak/Faker.js/ to generate fake data from within the `init-mongo.js` script to populate a local test MongoDB database. However I'm getting an error where I can't import the packages to be able to use the faker library or other npm libraries. Is there a way to do this from inside the container?

## `init-mongo.js`

```
const faker = require("faker");
const assert = require("assert");
```

my mongoDB configuration in Docker compose file is 

## docker-compose.yml
```
  mongodb:
    volumes:
      - "./backend/db/data:/data/db"
      - "./backend/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - "./backend/db/home/mongodb:/home/mongodb"
    command: mongod
    ports:
      - 27017:27017
      - 28017:28017
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} 
    restart: always
```
