### ISSUE TITLE
Parse errors if  `--dbpath`  and `--bind_ip` are omitted from docker-compose command 

### ISSUE THREAD

**Issue by Tuman829** [docker-library/mongo#441]
I am creating a mongo instance via docker-compose and I noticed that I was getting multiple `parse error: Invalid numeric literal at line 1, column 9` in the docker log on startup. After some research and experimentation I found the following (full files below): if I only had `--config /etc/mongod.conf` in the the command, I would get 6 parse errors. 

After adding `--dbpath /data/db` and `--bind_ip 127.0.0.1` these errors vanished. It looks like this is an issue with `JQ` in the `docker-entrypoint.sh` file, since the options I added to fix it are either defaults or already specified in my `mongod.conf` file. 

docker-compose.yml
```
version: '3.8'
services:
  mongo-db:
    image: 'mongo:4.4.1-bionic'
    command: --config /etc/mongod.conf --dbpath /data/db  --bind_ip 127.0.0.1
    container_name: 'lorem-mongo'
    environment:
     MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
     MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_DBDIR}:/data/db
      - ${MONGO_CONFIG_FILE}:/etc/mongod.conf
      - ./seed_data/:/home/seed_data
      - ${MONGO_CERTIFICATE}:/etc/ssl/test.pem
      - ${MONGO_CA}:/etc/ssl/ca.pem
```
mongod.conf
```
net:
   tls:
      mode: requireTLS
      certificateKeyFile: /etc/ssl/test.pem
      CAFile: /etc/ssl/ca.pem
systemLog:
   destination: file
   path: /var/log/mongodb/mongod.log
   logAppend: true
storage:
   journal:
      enabled: true
processManagement:
   fork: false
net:
   bindIp: 127.0.0.1
   port: 27017
security:
    authorization: enabled
setParameter:
   enableLocalhostAuthBypass: false
```

**Comment by tianon** [comment]
I copied your `mongo.conf` as `/temp.yml` inside a container, and found that our `js-yaml.js` library appears to be choking on your duplicated `net:` section:

```console
root@ad6ad4249bfc:/# mongo --norc --nodb --quiet --eval "load('/js-yaml.js'); printjson(jsyaml.load(cat('/temp.yml')))"
uncaught exception: YAMLException: duplicated mapping key at line 15, column -40:
    net:
    ^ :
YAMLException@/js-yaml.js:952:19
generateError@/js-yaml.js:1144:10
throwError@/js-yaml.js:1150:9
storeMappingPair@/js-yaml.js:1312:7
readBlockMapping@/js-yaml.js:2075:9
composeNode@/js-yaml.js:2336:12
readDocument@/js-yaml.js:2496:3
loadDocuments@/js-yaml.js:2552:5
load@/js-yaml.js:2573:19
@(shell eval):1:32
exiting with code -4
```

If you combine those two `net:` sections into one, `js-yaml.js` should be able to parse it properly:

```yaml
net:
   tls:
      mode: requireTLS
      certificateKeyFile: /etc/ssl/test.pem
      CAFile: /etc/ssl/ca.pem
   bindIp: 127.0.0.1
   port: 27017
systemLog:
   destination: file
   path: /var/log/mongodb/mongod.log
   logAppend: true
storage:
   journal:
      enabled: true
processManagement:
   fork: false
security:
    authorization: enabled
setParameter:
   enableLocalhostAuthBypass: false
```

```json
root@ad6ad4249bfc:/# mongo --norc --nodb --quiet --eval "load('/js-yaml.js'); printjson(jsyaml.load(cat('/temp.yml')))"
{
	"net" : {
		"tls" : {
			"mode" : "requireTLS",
			"certificateKeyFile" : "/etc/ssl/test.pem",
			"CAFile" : "/etc/ssl/ca.pem"
		},
		"bindIp" : "127.0.0.1",
		"port" : 27017
	},
	"systemLog" : {
		"destination" : "file",
		"path" : "/var/log/mongodb/mongod.log",
		"logAppend" : true
	},
	"storage" : {
		"journal" : {
			"enabled" : true
		}
	},
	"processManagement" : {
		"fork" : false
	},
	"security" : {
		"authorization" : "enabled"
	},
	"setParameter" : {
		"enableLocalhostAuthBypass" : false
	}
}
```

**Comment by tianon** [comment]
I've just opened #442 so we can surface this error message better (instead of it getting lost in `jq` instead).

I think https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys is an additional useful data point -- MongoDB is being generous in parsing this YAML and combining the configuration bits (which is not compliant with the YAML specification as of 1.1+).

**Comment by Tuman829** [comment]
The duplicate `net:` sections are taken from the [Mongo documentation](https://docs.mongodb.com/manual/tutorial/configure-ssl/#procedures-using-net-tls-settings), when I combine them I get errors when connecting to the instance.

**Comment by yosifkit** [comment]
While it is nice that `mongod` is generous in its parsing of the yaml config, we unfortunately use a different parser in the entrypoint script. The two best workarounds are to use yaml-spec compliant config file, or not use the entrypoint script (the parsing only happens when using `MONGO_INITDB_ROOT_USERNAME`/`_PASSWORD` and/or `/docker-entrypoint-initdb.d/`)

>when I combine them I get errors when connecting to the instance

The recombined config should work fine, but with its current values you'd be unable to connect to MongoDB outside of the `mongo-db` container since it is bound to `127.0.0.1`. Each container has its own IP address and separate `localhost` (via network namespaces), so neither the host nor other containers can connect to it. (You also won't be able to see the `mongod` logs via `docker logs`, since it is writing to a file rather than `stdout` to be captured by `docker`.)

```yaml
net:
   tls:
      mode: requireTLS
      certificateKeyFile: /etc/ssl/test.pem
      CAFile: /etc/ssl/ca.pem
   bindIp: 127.0.0.1
   port: 27017
systemLog:
   destination: file
   path: /var/log/mongodb/mongod.log
   logAppend: true
storage:
   journal:
      enabled: true
processManagement:
   fork: false
security:
    authorization: enabled
setParameter:
   enableLocalhostAuthBypass: false
```
