### ISSUE TITLE
High TTFB

### ISSUE THREAD

**Issue by PortStone** [docker-library/mongo#446]
My docker-compose.yml:
```
version: '3.1'

services:
  mongo_dev:
    container_name: "mongo_dev"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
    volumes:
      - "/opt/findnlink/db:/data/db"
    ports:
      - "27017:27017"
  node_dev:
    container_name: "node_dev"
    build: "./node"
    environment:
      - NODE_ENV=production
    ports:
      - 4000:4000
    depends_on:
      - mongo_dev
```

My string to connect to mongodb through mongoose on the node backend:
`mongodb+srv://<username>:<password>@mongo_dev/dev?retryWrites=true&w=majority`

Postman statistics:
![image](https://user-images.githubusercontent.com/27790087/101259484-2b9f9e80-3729-11eb-83c2-8473fc137303.png)

Note: I tried using MongoDB Atlas which resulted to normal speed behavior (300ms).
