### ISSUE TITLE
4.4.3: Server selection timeout in mongorestore script inside docker-entrypoint.sh

### ISSUE THREAD

**Issue by victortrusov** [docker-library/mongo#452]
Hi
I'm running mongorestore command to restore dump at the mongo container start using script in docker-entrypoint.sh folder, and it works perfectly in 4.4.2 version.

But I have an error in 4.4.3:
```
mongodb          | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/restore.sh
mongodb          | 2021-01-14T10:23:09.796+0000 error connecting to host: could not connect to server: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: localhost:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp 127.0.0.1:27017: connect: connection refused }, ] }
mongodb exited with code 1
```

docker-compose.yml
```
  mongodb:
    image: mongodb
    build: 
      context: ./db
      dockerfile: Dockerfile
    hostname: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    command: --bind_ip_all --quiet
```

db/Dockerfile
```
FROM mongo:4.4

COPY ./TestDB.agz /dump/
COPY ./restore.sh /docker-entrypoint-initdb.d/
RUN chmod 777 /docker-entrypoint-initdb.d/restore.sh

ENV MONGO_INITDB_DATABASE TestDB
```

db/restore.sh
```
mongorestore --gzip --archive=/dump/TestDB.agz
```
