### ISSUE TITLE
Allow override for /docker-entrypoint-initdb.d location 

### ISSUE THREAD

**Issue by gclayburg** [docker-library/mongo#460]
So i have been using this docker-compose.yml snippet for some time with success.  It starts up mongo with an user seeded that my app test can use:

```yml
version: '3'
services:
  mongo42:
    image: mongo:4.2.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      TZ: 'America/Denver'
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - "27017"
```
And this script in src/main/resources:

```js
db = db.getSiblingDB('synconsoledb');
db.createUser(
    {
        user: "synconsoledbuser",
        pwd: "supersecretpassword",
        roles: [
            { role: "readWrite", db: "synconsoledb" }
        ]
    }
);
```

This works with the regular bind mount.  What I'm running into now is that my environment has changed and I need to use a docker volume mount.  My javascript init file lives in a subdirectory of this volume mount.  As I understand it, you can't mount a subdirectory of a volume - you just mount the entire volume.  This is fine for the most part, but the issue here is that this docker-entrypoint.sh requires the init scripts to  be in this hardcoded directory: /docker-entrypoint-initdb.d/

It seems to me it might be helpful to add an extra environment variable named DOCKER_ENTRYPOINT_INITDB_DIR that could be used to override this directory location.  That way, you could use this docker image like this:

```yml
version: '3'
services:
  mongo42:
    image: registry:5000/mongoinit:4.2.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DOCKER_ENTRYPOINT_INITDB_DIR: /mycustomdir/src/main/resources
      TZ: 'America/Denver'
    volumes:
      - myvolume:/mycustomdir
    ports:
      - "27017"
```

I actually did this by creating my own image based off of mongo:4.2.12.  Would this be something others would want?  I could generate a PR if so.  It is actually a fairly small change and as far as i can tell, it shouldn't change the behavior of any existing use of this docker image.
