### ISSUE TITLE
container startup failed with `--config`

### ISSUE THREAD

**Issue by GavinTianYang** [docker-library/mongo#479]
Create container with: `docker run --name my_mongo -d mongo --config /etc/mongod.conf.orig`.
Container created but startup failed, and i can not get any logs when i execute `docker logs my_mongo`.
I want to create container with my own configuration.  but it did not work with the following example:
`$ docker run --name some-mongo -v /my/custom:/etc/mongo -d mongo --config /etc/mongo/mongod.conf`
I guess it was because of `--config `, but i did not get logs.

**Comment by yosifkit** [comment]
The package-provided config is likely having issues that configured paths do not exist. For example, `dbPath: /var/lib/mongodb`, which is different from the non-configured default of `/data/db`, which default the container image is designed to use.  You'd need to check that your provided config also doesn't configure paths that do not exist in the image or you will need to create them first (accessible for the `mongodb` user of the image).

**Comment by Declarcall** [comment]
You try to write like this
```
docker run --name mongo --restart=no \
-e MONGO_INITDB_ROOT_USERNAME=mongoadmin \
-e MONGO_INITDB_ROOT_PASSWORD=secret \
-p 27017:27017 \
-v /my/custom/mongo/data:/data/db \
-v /my/custom/mongo/logs:/data/log \
-v /my/custom/mongo/conf/mongod.conf:/etc/mongo-d/mongod.conf \
-d mongo:latest  --config /etc/mongo-d/mongod.conf
```
the mongod.conf config file contents :
```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /data/db
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /data/log/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
```

I tried and this configuration works successfully！
