### ISSUE TITLE
Mongo 5.0.0 crashes but 4.4.6 works

### ISSUE THREAD

**Issue by roadsidev** [docker-library/mongo#485]
EDIT: conclusion here https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

---

Already tried too many things and 5.0.0 (or latest) won't work on my Debian distro but it works fine on WSL2 (also Debian) for some reason. If I specify the 4.4.6 version it works great.

The latest version wont go up and will go on a restart loop. Docker logs are empty as well so I couldn't see what was happening.

![image](https://user-images.githubusercontent.com/6503047/125917494-01007ea1-b8ea-4b73-a2f5-e0b2599bbf0b.png)

My docker-compose.yml:
```
version: "3.8"
services:
 mongodb:
  image : mongo:latest
  container_name: mongodb
  environment:
  - PUID=1000
  - PGID=1000
  volumes:
  - /home/roadside/mongodb/database:/data/db
  ports:
  - 27017:27017
  restart: unless-stopped
```
