### ISSUE TITLE
Docker-compose volume mount has its permissions rewritten by mongo container

### ISSUE THREAD

**Issue by yutveg** [docker-library/mongo#492]
Hi,

I've got a basic MongoDB service defined in my docker-compose.yml (Using mongo:3.6 as the base image) 

```
database:
    build: database
    network_mode: "host"
    volumes:
      - ./database/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: celery
 ```
 
The database directory includes various WiredTiger files. The container will run without a problem, but any subsequent rebuilds result in a `PermissionDenied` error.
 
This is because after running, the MongoDB container overwrites the existing permissions of the files in `./database`, and leaves only read-access for the owner of the files (which becomes systemd during the overwriting process). When trying to then mount the directories again, Docker is unable to read them because Docker is not systemd.

Using chmod on the directories is a one-time solution, but obviously not ideal, and to my understanding there isn't a nice way to automate this within the docker process itself. 

I'm hoping this isn't an intentional feature of the mongo image itself because that seems pretty bizarre to me. If it is, what options does one have for persisting DB files on the host?
