### ISSUE TITLE
Introducing auth to already existing database

### ISSUE THREAD

**Issue by karloggb** [docker-library/mongo#496]
I used to have compose with no user/password specified:
```
  mongo:
    image: registry.gitlab.com/gideonbros/mongo:4
    container_name: mongodb
    hostname: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./srv/mongo-data:/data/db
    restart: always
```

But once I tried to introduce:
```
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
```
That did not work, because, the database was already created by the previous service instance. How would I migrate all the data to a database with auth (automatically if possible)?
