### ISSUE TITLE
Mongo image doesn't detect Auth typos

### ISSUE THREAD

**Issue by eyeamkd** [docker-library/mongo#499]
Mongo container was abruptly stopping without throwing any error when the Auth config on the docker-compose file had an environmental variable typo. It took me a while to realize the typo, until then the status was just showing "Exit(1)".
``` 
# This file is used for the shared configuration between the production and the development environments 
version: "3" 
services:
  node-app:
    build: .  
    ports:
      - "3000:3000" 
    environment: 
      - PORT=3000 
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eyeamkd
      - MONGO_INITDB_ROOT_PASSWORD=thiswasntthepassword
    volumes:
      - mongo-db:/data/db
volumes: 
  mongo-db:   
```

The typo was "INTI" instead of "INIT"
