### ISSUE TITLE
Docker compose startup script environment variables not preserved?

### ISSUE THREAD

**Issue by tamis-laan** [docker-library/mongo#503]
I'm trying to create a custom docker compose where I'm going to execute custom commands before starting mongod. However if I add the entry point the environment variables are no longer picked up! Not sure why this is happening?

``` yml 
 mongo:
    image: mongo:4.4
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      mongod
      "
```
