### ISSUE TITLE
Single node replica set KeyFile error

### ISSUE THREAD

**Issue by tamis-laan** [docker-library/mongo#504]
I'm trying to setup a single node replicaset for development using docker compose, see [docs](https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/) .

``` yml
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_REPLICA_SET_NAME: rs0
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c '
      echo "rs.initiate()" > /docker-entrypoint-initdb.d/init-replicaset.js;
      /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --bind_ip localhost
      '
```

When running I get the following:
```
mongo_1          | BadValue: security.keyFile is required when authorization is enabled with replica sets
mongo_1          | try 'mongod --help' for more information
```

But really I don't need a keyfile for a single node setup. Is there some way to disable this?
