### ISSUE TITLE
Change port using command when environment variables are set doesn't work

### ISSUE THREAD

**Issue by kevinimbrechts** [docker-library/mongo#507]
Hi,
When I try to start a MongoDB using another port than 27017 (eg 27020) and when I set environment variables like MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD, Mongo tries to init with port 27017.

How to say it to use port 27020 when the init starts ?

Here is my docker-compose.yaml file :
```yaml
version: '3'

services:
  mongodb:
    container_name: mongo
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxxxxxxx
      MONGO_INITDB_ROOT_PASSWORD: xxxxxxxxxxx
    volumes:
      - mdbdata:/data/db
      - /var/log/mongodb:/var/log/mongodb
    network_mode: host
    command: mongod --port 27020

volumes:
  mdbdata: {}
```

Many thanks
