### ISSUE TITLE
arm64v8 - 27 Illegal instruction

### ISSUE THREAD

**Issue by RT-Tap** [docker-library/mongo#510]
Hey,
 I tried running a basic mongoDB instance on a raspberrypi 4 8GB running ArchArm v8 using something as simple as : 
`docker run --name some-mongo -d mongo` 
or using docker-compose:
```
version: '3.8'
services:
  mongo:
    container_name: mongoDB-FinTechApp
    image: mongo
    command: --logappend --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: HvuTu!Kge28
    volumes:
      - "../databases:/data/db"
      - "./setupScripts:/docker-entrypoint-initdb.d"
    ports:
      - "192.168.1.254:27017:27017"
    networks:
      default:
        ipv4_address: 182.16.0.3
networks:
    default:
      ipam:
        driver: default
        config:
          - subnet: '182.16.0.0/16'
```

Each time I get the following error:

`
/usr/local/bin/docker-entrypoint.sh: line 392:    27 Illegal instruction     (core dumped) "${mongodHackedArgs[@]}" --fork
`

I thought this might be an architecture issue (even though the official image is tagged to support aarch64) so I tried the arm64v8 image specifically:  https://hub.docker.com/r/arm64v8/mongo however that gives me the same exact error.

Any idea or reason why this may be happening, and/or how to mitigate it?
