### ISSUE TITLE
Mongo 5.0.6 doesn't populate initial user

### ISSUE THREAD

**Issue by BrianAllred** [docker-library/mongo#524]
Not sure if this is a bug in the Docker image or upstream, but I'll start here.

Since the update to Mongo 5.0.6, my `init-mongo.sh` script doesn't populate my initial non-root user like it used to. Script below, logs attached.

`init-mongo.sh`
```
#!/bin/sh

mongosh -- "$MONGO_INITDB_DATABASE" <<EOF
    var rootUser = '$MONGO_INITDB_ROOT_USERNAME';
    var rootPassword = '$MONGO_INITDB_ROOT_PASSWORD';
    var admin = db.getSiblingDB('admin');
    admin.auth(rootUser, rootPassword);

    var user = '$MONGO_INITDB_USERNAME';
    var passwd = '$MONGO_INITDB_PASSWORD';
    db.createUser({user: user, pwd: passwd, roles: ["readWrite"]});
EOF
```

`docker-compose.yml`
```
version: "3"

services:

  mongo:
    image: mongo
    restart: always
    command: --port 27020
    ports:
      - 27020:27020
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: nowplaying
      MONGO_INITDB_PASSWORD: example
      MONGO_INITDB_DATABASE: spotify
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27020/
    networks:
      - mongo-network

networks:
  mongo-network:


```

[mongo-v5.0.6-logs.txt](https://github.com/docker-library/mongo/files/8171691/mongo-v5.0.6-logs.txt)
[mongo-v5.0.5-logs.txt](https://github.com/docker-library/mongo/files/8171692/mongo-v5.0.5-logs.txt)
