### ISSUE TITLE
ERROR: child process failed, exited with 1 when attach log file in docker-compose volumes

### ISSUE THREAD

**Issue by ITChelik** [docker-library/mongo#547]
I have this docker-compose file:
version: "3.7"
```
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
    volumes:
      - ./configs/mongo/mongod.conf:/etc/mongod.conf

```
And when im build and run tihs docker-compose file, and then checks logs for mongo, im see this errors:

>     mongo | about to fork child process, waiting until server is ready for connections.
>     mongo | forked process: 8
>     mongo | ERROR: child process failed, exited with 1
>     mongo | To see additional information in this output, start without the "--fork" option.

But if I comment line with config volume and line with entry point, everything works fine. But I need to have config file on host machine and proxy them to container. The config file I’m proxying took from [here](https://github.com/mongodb/mongo/blob/master/rpm/mongod.conf).
