### ISSUE TITLE
command replSetInitiate requires authentication

### ISSUE THREAD

**Issue by z514987467** [docker-library/mongo#550]
# docker-compose.yml
```
  rs_shard_server_01:
    image: mongo:5.0.9
    networks:
      - mongo-network
    container_name: rs_shard_server_01
    privileged: true
    restart: always
    ports:
      - 27118:27018
    command: mongod -f /mongod.conf
    volumes:
      - ${PWD}/shard1/mongod.conf:/mongod.conf
      - ${PWD}/shard1/data:/data
      - ${PWD}/mongodb.key:/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
         chmod 400 /mongodb.key
         chown 999:999 /mongodb.key
         exec docker-entrypoint.sh $$@
```
# mongod.conf
```
sharding:
  clusterRole: shardsvr
net:
  bindIpAll: true
  port: 27118
replication:
  replSetName: rs_shard_server_01
storage:
  dbPath: /data
  journal:
    enabled: true
security:
  keyFile: /mongodb.key
  authorization: enabled
```
# login and cmd
mongo --host 192.18.12.19 --port 27118
rs.initiate({
    _id: "rs_shard_server_01",
    members: [
      { _id : 0, host : "192.18.12.19:27118" },
      { _id : 1, host : "192.18.12.20:27118" },
      { _id : 2, host : "192.18.12.21:27118" },
    ]
});
# result message
{
        "ok" : 0,
        "errmsg" : "command replSetInitiate requires authentication",
        "code" : 13,
        "codeName" : "Unauthorized"
}
