### ISSUE TITLE
Version 6 issues with javascript on initialization script

### ISSUE THREAD

**Issue by hbazan-pp** [docker-library/mongo#569]
I have a docker compose set as:
```
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --auth
    volumes:
      - ./test/mongo/data/:/home/mongo/data/:ro
      - ./test/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
```
Where I dynamically read json files from the `/home/mongo/data/` folder, using `listFiles("/home/mongo/data/").forEach((f) => {...}`
This stopped working on version 6, I get:
`mongo  | ReferenceError: listFiles is not defined`
and the container fails to initialize

If I set image as `mongo:5` it works fine.
