### ISSUE TITLE
`exec format error` while starting `arm64v8/mongo:5-focal`

### ISSUE THREAD

**Issue by mglowinski93** [docker-library/mongo#573]
Hi,
I get error `exec /usr/local/bin/docker-entrypoint.sh: exec format error`, while trying to start `arm64v8/mongo:5-focal`.

Here is docker-compose file, which i use:
```
  mongo-database:
    image: "arm64v8/mongo:5-focal"
    hostname: MongoDB
    networks:
      backend-network:
    env_file:
      - .env.timezone
    container_name: mongo-database
```
I start it up with `docker-compose up --build` command.

I'm trying to set it up on RaspberryPi 3B+.

Any tips what can be wrong?
