### ISSUE TITLE
Mongo 6.0.2 - js files in docker-entrypoint-initdb.d no longer run

### ISSUE THREAD

**Issue by UglyHobbitFeet** [docker-library/mongo#580]
It looks like either some functionality got broken or there is a race condition going on where the js files in the docker-entrypoint-initdb.d folder don't get executed on initial startup.

I have the following setup:
 - docker-compose (tried both v1.29.2 and v2.12.1)
 - Docker (v20.10.21)

my-docker-compose.yml 

```
version: '3.8'
my-mongo:
  image: my-image/my-mongo
  command: mongod
  container_name: my-mongo
  ports:
    - 27017:27017
  build:
    context: ../my-mongo
  restart: always
  volumes:
    - /some/local/database/path:/data/db/
    - /some/local/script/path:/docker-entrypoint-initdb.d/:ro
```

Dockerfile

```
FROM mongo:6.0.2 as my-mongo
# Pretty sure the commands below don't actually work as shown later on in this ticket...
RUN chown -R root:root /data/db && chmod 755 -R /data/db
RUN chown -R root:root /docker-entrypoint-initdb.d && chmod 755 -R /docker-entrypoint-initdb.d
```

An example js file found in /some/local/script/path

```
db = new Mongo().getDB("myDb")
db.createCollection("someCollection");
db.someCollection.insert(someValidJson);
```

Verification:

```
docker exec -it my-mongo /bin/sh
ls -la
...
drwx------ someId someId docker-entrypoint-initdb.d

ls -la docker-entrypoint-initdb.d
-rwx------ someId someId example.js
... the rest of my js files


mongosh
show databases
<only shows admin,config,local>
```

ls -la from outside docker container (My own VM)

```
drwxr-xr-x polkitd root /some/local/database/path
drwx------ mySid mySid /some/local/script/path
```

Observations:
- There are no errors shown in the console output during docker-compose up for mongodb stuff
- I verified the files exist inside the container (shown above)
- I can manually cut/paste the contents of my js files into the mongosh shell and they execute fine. They correctly create the database/tables/etc, so the contents of the js file aren't the culprit
- I rm -rf the database folder before performing a docker-compose up to make sure the init scripts fire
- I have tried manually creating the database folder and docker-entrypoint-initdb.d folder outside of docker with root:root before running docker-compose up and have had no luck
- I have tried having no database folder and docker-entrypoint-initdb.d folder and letting them get auto-created during docker-compose-up and have had no luck
- This 'sometimes' works fine in v6.0.1 and I did not notice issue with it in v5. When it works I can grep the docker logs and see messages about it

```
   docker logs my-mongo | grep docker-entrypoint-initdb.d
   /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/<myFiles>.js
```

Any ideas/suggestions?
