### ISSUE TITLE
Cannot change default enviroment variables

### ISSUE THREAD

**Issue by CrisDgrnu** [docker-library/mongo#603]
I'm trying to setup a mongo container in a docker-compose file, here is the definition

```yml
mongodb:
        container_name: "mongo-test"
        image: mongo
        restart: always
        ports:
            - 27017:27017
        env_file:
            - docker.mongo.env
        networks:
            - dbnet
        volumes:
            - volume-test:/data/db
```

My env file

```env
MONGO_INITDB_ROOT_USERNAME=user
MONGO_INITDB_ROOT_PASSWORD=1234
```

The thing is that when I try to connect with Mongo Compass with the following connection string `mongodb://user:1234@localhost:27017` I get an **authentication failed** error. I can only connect with the instance if I use the default credentials **root/example**.

I have tried moving the env variables inside de `.yml` file but it still doesn't work. Running it raw it seems to work

`docker run -d --name mongo-test -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=user -e MONGO_INITDB_ROOT_PASSWORD=1234 mongo`
