### ISSUE TITLE
ERROR: child process failed, exited with 51

### ISSUE THREAD

**Issue by sebastiansterk** [docker-library/mongo#606]
Running the latest docker image (image id: a440572ac3c1 / tag 6.0.4 or latest) by using docker compose the process fails with the following error:
`ERROR: child process failed, exited with 51`

My docker compose file
```
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
```

Using image tag =<6.0.3 everything works fine.
