### ISSUE TITLE
Only one custom configuration file and environment variable is available

### ISSUE THREAD

**Issue by xiaoyang2626** [docker-library/mongo#618]
Only one custom configuration file and environment variable is available,when create a mongo: 6.0.5 container using the Docker Compose file

`docker compose yml`
```yml
version: "3.7"
services:
  mongo-web:
    image: mongo:6.0.5
    container_name: "mongo-web"
    hostname: "mw"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: VF20170701
    volumes:
      - "/software/docker/mongo/conf/:/etc/mongo/"
      - "/software/docker/mongo/data:/var/lib/mongo"
    ports:
      - "7027:7017"
    entrypoint: ["mongod", "--config", "/etc/mongo/mongod.conf"]
```

the `environment` is available if not `entrypoint`
