### ISSUE TITLE
Unable to init my docker mongo

### ISSUE THREAD

**Issue by agreenspan** [docker-library/mongo#627]
**Compose**
```
networks:
  docker_network:
    driver: bridge

services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    networks:
      docker_network:
        aliases:
          - mongo
          - mongodb
    env_file:
      - ./env/mongo.local.env
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
```

**Init**
```
/* eslint-disable no-undef */
print('-------------------Mongo Init Script-------------------');

print('Create DB');
db = db.getSiblingDB('cardeio-local');

print('Create User');
db.createUser({
  user: 'admin',
  pwd: 'cardeio',
  roles: [
    {
      role: 'readWrite',
      db: 'cardeio-local',
    },
  ],
});

print('Test Auth');
db.auth('admin', 'cardeio');

print('-------------------Mongo End Script--------------------');
```

**Error**
```
organized-play-api-mongodb-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/mongo-init.js
organized-play-api-mongodb-1  | MongoshInvalidInputError: [COMMON-10001] Invalid URI: cardeio-localit pull
```
