### ISSUE TITLE
Permission denied on bind-mounted config file in entrypoint

### ISSUE THREAD

**Issue by thomas-mckay** [docker-library/mongo#628]
Hello,

I'm using a docker-compose.yaml like so: 
```yaml
  mongodb:
    container_name: my-mongodb
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    tmpfs:
      - /data/configdb
      - /data/db
    command: mongod --config /etc/mongod.conf --oplogSize 8 --replSet rs0 --noauth
    healthcheck:
      test: bash -c "if mongo --eval 'quit(db.runCommand({ ping':' 1 }).ok ? 0 ':' 2)'; then exit 0; fi; exit 1;"
```

When I run `docker-compose up mongodb`, this is the output:
```
grep: /etc/mongod.conf: Permission denied
error: unexpected "js-yaml.js" output while parsing config:
Error: couldn't open file :
@(shell eval):1:44
exiting with code -4
```

Because I'm mounting the config file and `init-replica.sh` as bind mounts, the permissions on the files inside the container are the same as on my machine (660 for the config file and 770 for the script) but the owner is 1000:1000 (my local user) which doesn't exist inside the container. This is why I'm getting the error. If I `chown 999:999` both files locally, everything works as expected (999 is the uid/gid of the user/group `mongodb` inside the container). Another (cleaner) solution would be to `chmod 664/775` the files (I haven't tested, but that should work too).

I don't know if this needs fixing* or not but it should at least help others who encounter this problem.

(*) By fixing, I mean that maybe the entrypoint could ensure the permissions for `others` are set to the minimum required by the script (`r` / `r-x`) before switching users. Seems like not a great idea, as that means permissions are changed on the host too (bind-mount and all that). An other idea would be to create a group with the same gid as the group that owns the files and make the user `mongodb` a member of that group. That seems cleaner.
