### ISSUE TITLE
Add an example to documentation for "Initializing a fresh instance"

### ISSUE THREAD

**Issue by melvingaye** [docker-library/mongo#663]
## Problem

**Setting up a user and db (other than the admin user and test db) is a little opaque.**

This link [How to create a DB for MongoDB container on start up?](https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up) with over 268K views shows how much of an issue the lack of documentation is. There are many other variations of the search term above, so I'd imagine the numbers would be a lot higher if they were all tallied.

## Proposal

**Please include something like the below in that section of the documentation**

docker-compose.yaml

```yaml
version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: <admin user>
            MONGO_INITDB_ROOT_PASSWORD: <admin password>
            MONGO_INITDB_DATABASE: <custom db>
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
 ```

mongo-init.js
```js
print('Init Script - Started Adding the User Roles.');
// use the admin db to create a new user and give that new user permission to the db
// mongo seems to lazy load the db, meaning it'll create the db when a collection is first added
// but the newly created user will still have access to the db
db = db.getSiblingDB('admin');
db.createUser({
  user: '<custom user>',
  pwd: '<custom user password>',
  roles: [{ role: 'readWrite', db: '<custom db>' }],
});
print('Init Script - Ended Adding the User Roles.');
```

```sh
please include the shell version
```

**Comment by LaurentGoderre** [comment]
@melvingaye could you open a PR here: https://github.com/docker-library/docs/blob/master/mongo/content.md

**Comment by Spucis** [comment]
@melvingaye so its mandatory to do the db.getSibilings()? I don't understand it, if i have to specify the custom db in the script, what's the point to use the MONGO_INITDB_DATABASE environment variable in the first place?

Thanks in advance!

**Comment by drone1** [comment]
I'm losing my mind here.

Is there something I need to do to ensure that the root user is created on first startup?

Yes, I've read [the docs](https://hub.docker.com/_/mongo/).

I docker 'down', delete all volumes, all containers, even images, prune system -af – I have even reinstalled Docker, and I still cannot get mongo to create the root user in the auth database on startup.

run-servers.yml:
```
  mongodb:
    image: mongo:7.0.16
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password           # I've also tried with "password"
```

${PROJECT_ROOT}/dev.mongodb.conf:
```
net:
  port: 27017
  bindIp: 0.0.0.0  # Listen to all IP addresses

security:
  authorization: "enabled"
```

`docker-compose -f run-servers.yml up`

Servers start. Mongo doesn't print anything about a root user being created.

Does anyone know what I'm doing wrong here? 

```
mongosh localhost --port 27017 -u root -p password --authenticationDatabase
```

Nope, authentication failed.

I would really appreciate some help on this. I just lost my 3rd day trying to figure this out.

Thank you.
