### ISSUE TITLE
Not connecting in the mongodb compass

### ISSUE THREAD

**Issue by gulskr** [docker-library/mongo#674]
When i am trying run using the docker-compose.yml version 5.0.24 and I am doing all this in a ec2 server AWS @joshuajabbour 
```version: "3.0"  # Update the version to "3.0" as per your requirement

volumes:
  db-mongo-keys26:
  db-mongo-data-26:
  db-mongo-data-27:
  db-mongo-data-28:

networks:
  db-cluster26:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.10.21.0/24

services:

  db-mongo-keys26:
    image: depop/openssl-bats
    volumes:
      - db-mongo-keys26:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  # Node1
  db-mongo-node17:
    container_name: db-mongo-node17
    image: mongo:5.0.24  # Update the MongoDB version to "5.0.24"
    volumes:
      - db-mongo-keys26:/opt/keyfile
      - db-mongo-data-26:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017  # Change the host port to 27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-ppd'
    depends_on:
        - db-mongo-keys26
    networks:
      db-cluster26:
 
  # Node2
  db-mongo-node18:
    container_name: db-mongo-node18
    image: mongo:5.0.24
    volumes:
      - db-mongo-keys26:/opt/keyfile
      - db-mongo-data-27:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27017  # Change the host port to 27018
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-ppd'
    depends_on:
        - db-mongo-keys26
    networks:
      db-cluster26:
 
  # Node3
  db-mongo-node19:
    container_name: db-mongo-node19
    image: mongo:5.0.24
    volumes:
      - db-mongo-keys26:/opt/keyfile
      - db-mongo-data-28:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27017  # Change the host port to 27019
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-ppd'
    depends_on:
        - db-mongo-keys26
    networks:
      db-cluster26:```

This is to initiate the replica set 
```rs.initiate({
_id: "db-ppd",
   members: [
     {_id: 0, host: "db-mongo-node17:27017"},
     {_id: 1, host: "db-mongo-node18:27017"},
     {_id: 2, host: "db-mongo-node19:27017"}
   ]
 })```

And i have created a root user and trying to connect into my mongodb compass like this and this doesn't work it give an error - getaddrinfo ENOTFOUND db-mongo-node17
mongodb://root:*****@host_address:27017,host_address:27018,host_address:27018/?replicaSet=db-ppd

But when i try like this - it show me the db and work fine
mongodb://root:root@host_address:27017/?directConnection=true

I have no idea why this doesn't work when i don't try with the direct connection 

If anyone can help, it will be very much appreciated

**Comment by LaurentGoderre** [comment]
Connecting to the replicaset works from within the network. It seems to be an issue when connecting from outside.

**Comment by LaurentGoderre** [comment]
There are a few ways you could get around this problem. 

1) Implement a reverse proxy using nginx or similar. 
2) Add explicit ip addresses, change the ports mapping in the container and add the hosts to your hostfile,.

**Comment by LaurentGoderre** [comment]
The following worked for me

compose
```
version: "3.0"  # Update the version to "3.0" as per your requirement

volumes:
  db-mongo-keys26:
  db-mongo-data-26:
  db-mongo-data-27:
  db-mongo-data-28:

networks:
  db-cluster26:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.10.21.0/24

services:

  db-mongo-keys26:
    image: depop/openssl-bats
    volumes:
      - db-mongo-keys26:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  # Node1
  db-mongo-node17:
    container_name: db-mongo-node17
    image: mongo:5.0.24  # Update the MongoDB version to "5.0.24"
    volumes:
      - db-mongo-keys26:/opt/keyfile
      - db-mongo-data-26:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017  # Change the host port to 27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-ppd'
    depends_on:
        - db-mongo-keys26
 
  # Node2
  db-mongo-node18:
    container_name: db-mongo-node18
    image: mongo:5.0.24
    volumes:
      - db-mongo-keys26:/opt/keyfile
      - db-mongo-data-27:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27018  # Change the host port to 27018
    command: 'mongod --port 27018 --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-ppd'
    depends_on:
        - db-mongo-keys26
 
  # Node3
  db-mongo-node19:
    container_name: db-mongo-node19
    image: mongo:5.0.24
    volumes:
      - db-mongo-keys26:/opt/keyfile
      - db-mongo-data-28:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27019  # Change the host port to 27019
    command: 'mongod --port 27019 --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-ppd'
    depends_on:
        - db-mongo-keys26
 ```

Command:
```
rs.initiate({
_id: "db-ppd",
   members: [
     {_id: 0, host: "db-mongo-node17:27017"},
     {_id: 1, host: "db-mongo-node18:27018"},
     {_id: 2, host: "db-mongo-node19:27019"}
   ]
 })
```

Host file on host

```
127.0.0.1       db-mongo-node17
127.0.0.1       db-mongo-node18
127.0.0.1       db-mongo-node19
```

Connection string:

```
mongodb://root:example@db-mongo-node17:27017,db-mongo-node18:27018,db-mongo-node19:27019/?replicaSet=db-ppd
```
