### ISSUE TITLE
Is this a vulnerability? Under the set credentials, the client does not have credentials to connect but cannot operate

### ISSUE THREAD

**Issue by InfernalAzazel** [docker-library/mongo#699]
server docker-compose.yml
```yml
version: '3.9'
services:
  # 数据库
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    command: --auth

volumes:
  mongo_data:
    name: mongo_data
```
Local testing

![image](https://github.com/docker-library/mongo/assets/40333954/cdf28ae9-d6ff-419f-8beb-878a94cddf5b)

![image](https://github.com/docker-library/mongo/assets/40333954/86d52ff5-4b19-4d4a-ac2b-cedb5a7b7679)

![image](https://github.com/docker-library/mongo/assets/40333954/079dc7e0-84cd-4061-9a9a-5b7bc2be5041)

Vulnerability scanner classified as CVE-1999-0633
