### ISSUE TITLE
Custom configuration file

### ISSUE THREAD

**Issue by codingwithoutcomments** [docker-library/mongo#76]
How would one go about loading a custom configuration file using this docker image?

**Comment by ozlerhakan** [comment]
Using the data volume approach you can load your custom config file into your container, something like the following one:

```
$docker run --name mongo -d -v your/host/dir:/container/dir mongo:3.2 mongod -f /container/dir/mongod.conf
```

if this is what you need.

**Comment by jolestar** [comment]
@ozlerhakan  I use this command to run,  container exit in second, and no log.

**Comment by ozlerhakan** [comment]
@jolestar  Here is a working command that I use on windows 10 if your docker host resides in a virtualbox,

```
$ docker run --name mongo -d -v //c/Users/Hakan/config:/mongodb mongo:3.2  mongod -f //mongodb/mongod.conf
```

**Comment by jolestar** [comment]
@ozlerhakan  thanks reply.
I find the reason, my mongod.conf include systemLog config option, I try comment it,  the command works. but I do not know why.

**Comment by ozlerhakan** [comment]
@jolestar I forgot to show you an example of a config file, see this for example:

```
storage:
  dbPath: /data/db
  directoryPerDB: true
  journal:
    enabled: true
  engine: wiredTiger

net:
  port: 27017
```

But if you have the systemLog section, you cannot see anything when doing docker logs : 
```
storage:
  dbPath: /data/db
  directoryPerDB: true
  journal:
    enabled: true
  engine: wiredTiger

systemLog:
  destination: file
  logAppend: false
  path: /data/mongod.log
```
